name: system_theme
description: A plugin to get the current system theme info. Supports Android, Web, Windows, Linux and macOS
version: 2.2.0
repository: https://github.com/bdlukaa/system_theme

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  system_theme_web: ^0.0.2
    # path: system_theme_web/
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SystemThemePlugin
      macos:
        package: com.bruno.system_theme
        pluginClass: SystemThemePlugin
      android:
        package: com.bruno.system_theme
        pluginClass: SystemThemePlugin
      web:
        default_package: system_theme_web
      linux:
        package: com.bruno.system_theme
        pluginClass: SystemThemePlugin
